Not a conda environment: /home/pj321/electrolyte_env
Changed directory to /home/pj321/~ml_physics/electrolytes/electrolytes/data/results/1080.

JobID: 21845716
======
Time: Sat 11 Apr 16:06:52 BST 2020
Running on master node: cpu-e-106
Current directory: /home/pj321/~ml_physics/electrolytes/electrolytes/data/results/1080

Nodes allocated:
================
cpu-e-106

numtasks=32, numnodes=1, mpi_tasks_per_node=32 (OMP_NUM_THREADS=1)

Executing command:
==================
mpirun -ppn 32 -np 32 bash ./run2.sh 

mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
mkdir: cannot create directory ‘bs020_is010’: File exists
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "../../../../descriptor_generator.py", line 13, in <module>
    from data_utils import dists
  File "/home/pj321/~ml_physics/electrolytes/electrolytes/data_utils.py", line 3, in <module>
    from scipy.stats import norm
ModuleNotFoundError: No module named 'scipy'
